{
 "title": "AirOS Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": {
     "query": "label_values(airos_device_uptime_s, device)"
    }
   },
   {
    "name": "station",
    "query": {
     "query": "label_values(airos_sta_info, remote_device)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(airos_if_mtu, if_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "AirOS Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Signal Quality",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "airos_sta_signal{device=~\"$device\",remote_device=~\"$station\"}",
     "legendFormat": "{{device}} -> {{remote_device}}"
    }
   ]
  },
  {
   "title": "AirOS Device Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "airos_wireless_throughput_kbps{device=~\"$device\",direction=\"tx\"}",
     "legendFormat": "{{device}} {{direction}}"
    },
    {
     "expr": "airos_wireless_throughput_kbps{device=~\"$device\",direction=\"rx\"} * -1",
     "legendFormat": "{{device}} {{direction}}"
    }
   ]
  },
  { "title": "$device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "device" },
  {
   "title": "AirOS Device Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "airos_device_uptime_s{device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airos_device_uptime_s{device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airos_device_load_avg{device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Mem Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airos_device_ram_usage_percent{device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(airos_if_mtu{device=~\"$device\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Stations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airos_wireless_station_count{device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airos_wireless_service_uptime_perc{device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Transmit Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airos_wireless_tx_power_dbm{device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airos_wireless_frequency{device=~\"$device\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "AirOS Wireless Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "airos_wireless_info{device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "Downlink Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airos_wireless_capacity_dl_kbit{device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "Signal Quality",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "airos_wireless_noise_floor{device=\"$device\"}",
     "legendFormat": "Noise Floor"
    },
    {
     "expr": "airos_sta_signal{device=~\"$device\"}",
     "legendFormat": "{{remote_device}} Signal"
    }
   ]
  },
  {
   "title": "Uplink Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airos_wireless_capacity_ul_kbit{device=~\"$device\"}"
    }
   ]
  },
  {
   "title": "AirOS Station List",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "airos_sta_info{device=~\"$device\",remote_device=~\"$station\"}"
    }
   ]
  },
  {
   "title": "Station Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(airos_sta_bytes{device=~\"$device\",direction=\"tx\"}[$__rate_interval])",
     "legendFormat": "{{remote_device}} TX"
    },
    {
     "expr": "rate(airos_sta_bytes{device=~\"$device\",direction=\"rx\"}[$__rate_interval]) * -1",
     "legendFormat": "{{remote_device}} RX"
    }
   ]
  },
  {
   "title": "Station Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "airos_sta_tx_latency_ms{device=~\"$device\", remote_device=~\"$station\"}",
     "legendFormat": "{{remote_device}}"
    }
   ]
  },
  {
   "title": "AirOS Interface Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "airos_if_mtu{device=~\"$device\",if_name=~\"$interface\"}"
    }
   ]
  }
 ]
}